const PLAINTEXTS = [
  "TO BE OR NOT TO BE THAT IS THE QUESTION WHETHER TIS NOBLER IN THE MIND TO SUFFER THE SLINGS AND ARROWS OF OUTRAGEOUS FORTUNE",
  "ALL THAT GLITTERS IS NOT GOLD OFTEN HAVE YOU HEARD THAT TOLD MANY A MAN HIS LIFE HATH SOLD BUT MY OUTSIDE TO BEHOLD",
  "NOW IS THE WINTER OF OUR DISCONTENT MADE GLORIOUS SUMMER BY THIS SUN OF YORK AND ALL THE CLOUDS THAT LOURED UPON OUR HOUSE",
  "BUT SOFT WHAT LIGHT THROUGH YONDER WINDOW BREAKS IT IS THE EAST AND JULIET IS THE SUN ARISE FAIR SUN AND KILL THE ENVIOUS MOON",
  "FRIENDS ROMANS COUNTRYMEN LEND ME YOUR EARS I COME TO BURY CAESAR NOT TO PRAISE HIM THE EVIL THAT MEN DO LIVES AFTER THEM",
  "DOUBLE DOUBLE TOIL AND TROUBLE FIRE BURN AND CAULDRON BUBBLE FILLET OF A FENNY SNAKE IN THE CAULDRON BOIL AND BAKE",
  "CALL ME ISHMAEL SOME YEARS AGO NEVER MIND HOW LONG PRECISELY HAVING LITTLE OR NO MONEY IN MY PURSE AND NOTHING PARTICULAR",
  "IT WAS THE BEST OF TIMES IT WAS THE WORST OF TIMES IT WAS THE AGE OF WISDOM IT WAS THE AGE OF FOOLISHNESS",
  "IT IS A TRUTH UNIVERSALLY ACKNOWLEDGED THAT A SINGLE MAN IN POSSESSION OF A GOOD FORTUNE MUST BE IN WANT OF A WIFE",
  "IN THE BEGINNING GOD CREATED THE HEAVEN AND THE EARTH AND THE EARTH WAS WITHOUT FORM AND VOID AND DARKNESS WAS UPON THE FACE",
  "WE THE PEOPLE OF THE UNITED STATES IN ORDER TO FORM A MORE PERFECT UNION ESTABLISH JUSTICE INSURE DOMESTIC TRANQUILITY",
  "FOUR SCORE AND SEVEN YEARS AGO OUR FATHERS BROUGHT FORTH ON THIS CONTINENT A NEW NATION CONCEIVED IN LIBERTY",
  "GIVE ME LIBERTY OR GIVE ME DEATH THE CRY STILL ECHOES WHEN PEOPLE REFUSE TO YIELD THEIR RIGHTS",
  "EARLY TO BED AND EARLY TO RISE MAKES A PERSON HEALTHY WEALTHY AND WISE",
  "A JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP AND CONTINUES ONE STEP AT A TIME",
  "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG WHILE JACKDAWS LOVE MY BIG SPHINX OF QUARTZ",
  "HONESTY IS THE BEST POLICY AND FORTUNE FAVORS THE BOLD WHEN PREPARATION MEETS OPPORTUNITY",
  "PRACTICE AND PERSEVERANCE OPEN DOORS THAT TALENT ALONE MAY NEVER UNLOCK",
  "KNOWLEDGE SPEAKS BUT WISDOM LISTENS AND PATIENCE OFTEN HEARS WHAT HASTE MISSES",
  "NO ACT OF KINDNESS HOWEVER SMALL IS EVER WASTED AND GOOD HABITS GROW STRONGER WITH USE",
  "THE RAIN IN SPAIN STAYS MAINLY IN THE PLAIN AND THE TRAIN ARRIVES AGAIN AT DAWN",
  "MEASURE TWICE CUT ONCE AND ALWAYS LEAVE ROOM TO IMPROVISE WHEN THE PLAN MEETS THE WORLD",
  "TWINKLE TWINKLE LITTLE STAR HOW I WONDER WHAT YOU ARE UP ABOVE THE WORLD SO HIGH LIKE A DIAMOND IN THE SKY",
  "HUMPTY DUMPTY SAT ON A WALL HUMPTY DUMPTY HAD A GREAT FALL ALL THE KINGS HORSES AND ALL THE KINGS MEN",
  "JACK AND JILL WENT UP THE HILL TO FETCH A PAIL OF WATER JACK FELL DOWN AND BROKE HIS CROWN",
  "MARY HAD A LITTLE LAMB ITS FLEECE WAS WHITE AS SNOW AND EVERYWHERE THAT MARY WENT THE LAMB WAS SURE TO GO",
  "BAA BAA BLACK SHEEP HAVE YOU ANY WOOL YES SIR YES SIR THREE BAGS FULL",
  "HEY DIDDLE DIDDLE THE CAT AND THE FIDDLE THE COW JUMPED OVER THE MOON",
];

import { MAX_TEXT_LENGTH } from "./constants.js";

export function randomPlaintext() {
  const pool = [...PLAINTEXTS];
  const parts = [];

  while (pool.length > 0 && parts.join(" ").length < MAX_TEXT_LENGTH) {
    const index = Math.floor(Math.random() * pool.length);
    parts.push(pool.splice(index, 1)[0]);
  }

  if (parts.length === 0) return "";

  let mixed = parts.join(" ");

  while (mixed.length < MAX_TEXT_LENGTH) {
    const next = PLAINTEXTS[Math.floor(Math.random() * PLAINTEXTS.length)];
    mixed += " " + next;
  }

  return mixed.slice(0, MAX_TEXT_LENGTH);
}
