const PLAINTEXTS = [
  "TO BE OR NOT TO BE THAT IS THE QUESTION WHETHER TIS NOBLER IN THE MIND TO SUFFER THE SLINGS AND ARROWS OF OUTRAGEOUS FORTUNE",
  "ALL THAT GLITTERS IS NOT GOLD OFTEN HAVE YOU HEARD THAT TOLD MANY A MAN HIS LIFE HATH SOLD BUT MY OUTSIDE TO BEHOLD",
  "NOW IS THE WINTER OF OUR DISCONTENT MADE GLORIOUS SUMMER BY THIS SUN OF YORK AND ALL THE CLOUDS THAT LOURED UPON OUR HOUSE",
  "BUT SOFT WHAT LIGHT THROUGH YONDER WINDOW BREAKS IT IS THE EAST AND JULIET IS THE SUN ARISE FAIR SUN AND KILL THE ENVIOUS MOON",
  "FRIENDS ROMANS COUNTRYMEN LEND ME YOUR EARS I COME TO BURY CAESAR NOT TO PRAISE HIM THE EVIL THAT MEN DO LIVES AFTER THEM",
  "DOUBLE DOUBLE TOIL AND TROUBLE FIRE BURN AND CAULDRON BUBBLE FILLET OF A FENNY SNAKE IN THE CAULDRON BOIL AND BAKE",
  "CALL ME ISHMAEL SOME YEARS AGO NEVER MIND HOW LONG PRECISELY HAVING LITTLE OR NO MONEY IN MY PURSE AND NOTHING PARTICULAR",
  "IT WAS THE BEST OF TIMES IT WAS THE WORST OF TIMES IT WAS THE AGE OF WISDOM IT WAS THE AGE OF FOOLISHNESS",
  "IT IS A TRUTH UNIVERSALLY ACKNOWLEDGED THAT A SINGLE MAN IN POSSESSION OF A GOOD FORTUNE MUST BE IN WANT OF A WIFE",
  "IN THE BEGINNING GOD CREATED THE HEAVEN AND THE EARTH AND THE EARTH WAS WITHOUT FORM AND VOID AND DARKNESS WAS UPON THE FACE",
];

const MAX_TEXT_LENGTH = 256;

export function randomPlaintext() {
  const pool = [...PLAINTEXTS];
  const parts = [];

  while (pool.length > 0 && parts.join(" ").length < MAX_TEXT_LENGTH) {
    const index = Math.floor(Math.random() * pool.length);
    parts.push(pool.splice(index, 1)[0]);
  }

  if (parts.length === 0) return "";

  let mixed = parts.join(" ");

  while (mixed.length < MAX_TEXT_LENGTH) {
    const next = PLAINTEXTS[Math.floor(Math.random() * PLAINTEXTS.length)];
    mixed += " " + next;
  }

  return mixed.slice(0, MAX_TEXT_LENGTH);
}
